
//Upload
const ACTION_UPLOAD_ADD_FILE = 'ACTION_UPLOAD_ADD_FILE';
const ACTION_UPLOAD_REMOVE_FILE = 'ACTION_UPLOAD_REMOVE_FILE';

//Home
const ACTION_HOME_ADD_ITEMS = 'ACTION_HOME_ADD_ITEMS';
const ACTION_HOME_BEGIN_LOADING = 'ACTION_HOME_BEGIN_LOADING';
const ACTION_HOME_LOADING_FINISH = 'ACTION_HOME_LOADING_FINISH';
const ACTION_HOME_NO_MORE = 'ACTION_HOME_NO_MORE';
const ACTION_HOME_CHANGE_TAB = 'ACTION_HOME_CHANGE_TAB';

//Video
const ACTION_VIDEO_ADD_ITEMS = 'ACTION_VIDEO_ADD_ITEMS';
const ACTION_VIDEO_BEGIN_LOADING = 'ACTION_VIDEO_BEGIN_LOADING';
const ACTION_VIDEO_LOADING_FINISH = 'ACTION_VIDEO_LOADING_FINISH';
const ACTION_VIDEO_NO_MORE = 'ACTION_VIDEO_NO_MORE';
const ACTION_VIDEO_CHANGE_TAB = 'ACTION_VIDEO_CHANGE_TAB';

//P2P share
const ACTION_P2P_SHARE_ADD_TORRENT = 'ACTION_P2P_SHARE_ADD_TORRENT';
const ACTION_P2P_SHARE_UPDATE_CLIENT_INFO = 'ACTION_P2P_SHARE_UPDATE_CLIENT_INFO';
const ACTION_P2P_SHARE_REMOVE_TORRENT = 'ACTION_P2P_SHARE_REMOVE_TORRENT';
const ACTION_P2P_SHARE_CHANGE_STATE = 'ACTION_P2P_SHARE_CHANGE_STATE';
const ACTION_P2P_SHARE_STATE_NORMAL = 'ACTION_P2P_SHARE_STATE_NORMAL';
const ACTION_P2P_SHARE_STATE_ADD_UPLOAD_ING = 'ACTION_P2P_SHARE_STATE_ADD_UPLOAD_ING';
const ACTION_P2P_SHARE_STATE_ADD_DOWNLOAD_ING = 'ACTION_P2P_SHARE_STATE_ADD_DOWNLOAD_ING';

//Detail
const ACTION_DETAIL_UPDATE_RESOURCE_INFO = 'ACTION_DETAIL_UPDATE_RESOURCE_INFO';

//Little Tool
const ACTION_LITTLE_TOOL_ADD_ITEMS = 'ACTION_LITTLE_TOOL_ADD_ITEMS';

//Header
const ACTION_HEADER_CHANGE_SELECTED_KEY = 'ACTION_HEADER_CHANGE_SELECTED_KEY';

//SearchResult
const ACTION_SEARCH_RESULT_ADD_ITEMS = 'ACTION_SEARCH_RESULT_ADD_ITEMS';
const ACTION_SEARCH_RESULT_BEGIN_LOADING = 'ACTION_SEARCH_RESULT_BEGIN_LOADING';
const ACTION_SEARCH_RESULT_LOADING_FINISH = 'ACTION_SEARCH_RESULT_LOADING_FINISH';
const ACTION_SEARCH_RESULT_NO_MORE = 'ACTION_SEARCH_RESULT_NO_MORE';
const ACTION_SEARCH_RESULT_CHANGE_TAB = 'ACTION_SEARCH_RESULT_CHANGE_TAB';
const ACTION_SEARCH_RESULT_UPDATE_KEYWORDS = 'ACTION_SEARCH_RESULT_UPDATE_KEYWORDS';


//shareWebsite
const ACTION_SHARE_WEBSITE_CHANGE_FIELDS = 'ACTION_SHARE_WEBSITE_CHANGE_FIELDS';
const ACTION_SHARE_WEBSITE_BEGIN_SHARE = 'ACTION_SHARE_WEBSITE_BEGIN_SHARE';
const ACTION_SHARE_WEBSITE_FINISH_SHARE = 'ACTION_SHARE_WEBSITE_FINISH_SHARE';

export {
    ACTION_UPLOAD_ADD_FILE,
    ACTION_P2P_SHARE_ADD_TORRENT,
    ACTION_P2P_SHARE_UPDATE_CLIENT_INFO,
    ACTION_P2P_SHARE_REMOVE_TORRENT,
    ACTION_P2P_SHARE_CHANGE_STATE,
    ACTION_P2P_SHARE_STATE_ADD_DOWNLOAD_ING,
    ACTION_P2P_SHARE_STATE_ADD_UPLOAD_ING,
    ACTION_P2P_SHARE_STATE_NORMAL,
    ACTION_HOME_ADD_ITEMS,
    ACTION_HOME_BEGIN_LOADING,
    ACTION_HOME_LOADING_FINISH,
    ACTION_HOME_NO_MORE,
    ACTION_UPLOAD_REMOVE_FILE,
    ACTION_DETAIL_UPDATE_RESOURCE_INFO,
    ACTION_HOME_CHANGE_TAB,
    ACTION_VIDEO_ADD_ITEMS,
    ACTION_VIDEO_BEGIN_LOADING,
    ACTION_VIDEO_CHANGE_TAB,
    ACTION_VIDEO_LOADING_FINISH,
    ACTION_VIDEO_NO_MORE,
    ACTION_LITTLE_TOOL_ADD_ITEMS,
    ACTION_HEADER_CHANGE_SELECTED_KEY,
    ACTION_SEARCH_RESULT_ADD_ITEMS,
    ACTION_SEARCH_RESULT_BEGIN_LOADING,
    ACTION_SEARCH_RESULT_CHANGE_TAB,
    ACTION_SEARCH_RESULT_LOADING_FINISH,
    ACTION_SEARCH_RESULT_NO_MORE,
    ACTION_SEARCH_RESULT_UPDATE_KEYWORDS,
    ACTION_SHARE_WEBSITE_CHANGE_FIELDS,
    ACTION_SHARE_WEBSITE_BEGIN_SHARE,
    ACTION_SHARE_WEBSITE_FINISH_SHARE,
}